//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeduShop.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Orders")]
    public partial class Orders
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public byte[] Phone { get; set; }
        [Required]
        public string Message { get; set; }
        [Required]
        public DateTime CreateDate { get; set; }
        [Required]
        public string CreateBy { get; set; }
        [Required]
        public string PayMentMeThod { get; set; }
        [Required]
        public string PayMentStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        [ForeignKey("ID")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
