//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeduShop.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Pages")]
    public partial class Pages
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int ID { get; set; }
        [Required]
        [MaxLength(250)]
        public string Name { get; set; }
        [Column(TypeName ="varchar")]
        [MaxLength(256)]
        [Required]
        public string Alias { set; get; }
        [Required]
        public string Content { get; set; }
        //[Required]
        //public string MetaKeyword { get; set; }
        //[Required]
        //public string MetaDescriptiom { get; set; }
        //public Nullable<bool> Status { get; set; }
    }
}
